### PR TITLE
1. add back map center for prediction purpose

### PR DESCRIPTION
**Pull request by Alan-LanFeng**
## What changes do you make in this PR?

* Add global center back in nuScenes.

## Checklist

* [ ] I have merged the latest main branch into current branch.
* [ ] I have run `bash scripts/format.sh` before merging.
* [ ] I updated documentation, if there are related change
* [ ] I add tests if there are new functions or bug-fixing
* Please use "squash and merge" mode.

### CODE REVIEW

**Comment by QuanyiLi** [comment]
We normalize the nuScenes scenarios with the ego car's initial position as the [0 ,0] origin. Having this global center, it seems we can restore the original coordinates right?

**Comment by Alan-LanFeng** [comment]
> We normalize the nuScenes scenarios with the ego car's initial position as the [0 ,0] origin. Having this global center, it seems we can restore the original coordinates right?
Yes. This aligns with the processing of Waymo and AV2. Having the original coordinates is necessary for official toolkit in prediction.

**Comment by QuanyiLi** [comment]
Ahh, do we have this in other converters? If not, we have to append this information...

**Comment by Alan-LanFeng** [comment]
Seems that only in nuScenes the coordinates are normalized to (0,0), while other converters keep the coordinates in the original coordinate frame

**Comment by QuanyiLi** [comment]
Great!

**Pull request merged**
